services:
  test-broker:
    build: test-broker/.
    ports:
      - "1883:1883"
  test-cache:
    build: test-cache/.
    ports:
      - "80:80"
    environment:
      - FAIL_RATE=0
      - NGINX_HOST=obsproc-test-env.wis2-testing.net

    volumes:
      - ./test-data/${NOTIFICATION_DATA_DIR}:/usr/share/nginx/html/data/cache/a/ru-aviamettelecom/data/core/weather/surface-based-observations/synop
    

  test-node:
    build: test-node/.

    command: tail -F anything

    environment:
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
      - CONTENT_INTEGRATED_RATE=${CONTENT_INTEGRATED_RATE}
      - INTEGRITY_CHECKSUM_RATE=${INTEGRITY_CHECKSUM_RATE}
      - INTEGRITY_LENGTH_CONTENT_RATE=${INTEGRITY_LENGTH_CONTENT_RATE}
      - INTEGRITY_LENGTH_LINK_RATE=${INTEGRITY_LENGTH_LINK_RATE}
      - INTEGRITY_SCHEMA_RATE=${INTEGRITY_SCHEMA_RATE}
      - INTEGRITY_PUBDATE_RATE=${INTEGRITY_PUBDATE_RATE}
      - INTEGRITY_NO_DATAID_RATE=${INTEGRITY_NO_DATAID_RATE}
      - NR_DUPLICATES_MAX=${NR_DUPLICATES_MAX} # no duplicates
      - NR_DUPLICATES_MIN=${NR_DUPLICATES_MIN} # no duplicates
      - DUPLICATE_MAX_DELAY_MS=${DUPLICATE_MAX_DELAY_MS}
      - NR_CACHES=${NR_CACHES} # only one cache simulated
      - MSG_RATE_PER_SECOND=${MSG_RATE_PER_SECOND}
      - MAX_MESSAGES=${MAX_MESSAGES}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_DOMAIN=${CACHE_DOMAIN}
      - DATA_DIR=/data
      - TEST_ID=${TEST_ID}

    volumes: 
      - ./test-data/${NOTIFICATION_DATA_DIR}:/data
      - ./test-node:/app
